export const RANKS = [
  { key: "OLYMPIAN", label: "Olympian", color: "#5DD9E8" },
  { key: "TITAN_III", label: "Titan III", color: "#E63946" },
  { key: "TITAN_II", label: "Titan II", color: "#E63946" },
  { key: "TITAN_I", label: "Titan I", color: "#E63946" },
  { key: "CHAMPION_III", label: "Champion III", color: "#C77DFF" },
  { key: "CHAMPION_II", label: "Champion II", color: "#C77DFF" },
  { key: "CHAMPION_I", label: "Champion I", color: "#C77DFF" },
  { key: "DIAMOND_III", label: "Diamond III", color: "#7B9FE8" },
  { key: "DIAMOND_II", label: "Diamond II", color: "#7B9FE8" },
  { key: "DIAMOND_I", label: "Diamond I", color: "#7B9FE8" },
  { key: "PLATINUM_III", label: "Platinum III", color: "#4ECDC4" },
  { key: "PLATINUM_II", label: "Platinum II", color: "#4ECDC4" },
  { key: "PLATINUM_I", label: "Platinum I", color: "#4ECDC4" },
  { key: "GOLD_III", label: "Gold III", color: "#F4C430" },
  { key: "GOLD_II", label: "Gold II", color: "#F4C430" },
  { key: "GOLD_I", label: "Gold I", color: "#F4C430" },
  { key: "SILVER_III", label: "Silver III", color: "#C0D6DF" },
  { key: "SILVER_II", label: "Silver II", color: "#C0D6DF" },
  { key: "SILVER_I", label: "Silver I", color: "#C0D6DF" },
  { key: "BRONZE_III", label: "Bronze III", color: "#CD7F32" },
  { key: "BRONZE_II", label: "Bronze II", color: "#CD7F32" },
  { key: "BRONZE_I", label: "Bronze I", color: "#CD7F32" },
  { key: "WOOD_III", label: "Wood III", color: "#8B4513" },
  { key: "WOOD_II", label: "Wood II", color: "#8B4513" },
  { key: "WOOD_I", label: "Wood I", color: "#8B4513" },
];
